# Generated by Django 4.1.6 on 2023-09-26 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fen', models.TextField(blank=True)),
                ('added', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
